version: '3.4'

services:
  cinema-api-rest:
    image: cinema-api-rest
    build:
      context: .
      dockerfile: src/Cinema.Api.Rest/Dockerfile
    ports:
      - "5000:80"
    depends_on:
      - redis

  cinema-api-grpc:
    image: cinema-api-grpc
    build:
      context: .
      dockerfile: src/Cinema.Api.Grpc/Dockerfile
    ports:
      - "5001:80"
    depends_on:
      - redis
  redis:
    image: "redis:6.0"
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/data

volumes:
  redisdata:
