version: '3.8'

services:
  cinema-api-rest:
    build:
      context: ../src
      dockerfile: Cinema.Api.Rest/Dockerfile
    ports:
      - "5000:80"
    depends_on:
      - redis
 
  cinema-api-grpc:
    build:
      context: ../src
      dockerfile: Cinema.Api.gRPC/Dockerfile
    ports:
      - "5001:80"
    depends_on:
      - redis

  redis:
    image: "redis:6.0"
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/data

volumes:
  redisdata:
